modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "the_afterdark"
version = "${version}"
displayName = "The Afterdark"
authors = "DenisMasterHerobrine, VeiTr"
description = '''
A dimension Minecraft mod related to the afterlife, the dark, and the unknown.
'''
#logoFile = ""

[[dependencies.the_afterdark]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.the_afterdark]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
